In [2]:
import pandas as pd
from pathlib import Path

csv_path = Path.home() / "Desktop" / "csv"

dim_date = pd.read_csv(csv_path / "dim_date.csv")
dim_department = pd.read_csv(csv_path / "dim_department.csv")
dim_employee = pd.read_csv(csv_path / "dim_employee.csv")
dim_employee_snapshot = pd.read_csv(csv_path / "dim_employee_snapshot.csv")
dim_job_role = pd.read_csv(csv_path / "dim_job_role.csv")
fact_attrition = pd.read_csv(csv_path / "fact_attrition.csv")

# Data Inspaction

In [3]:
print("dim_date:", dim_date.shape)
print("dim_department:", dim_department.shape)
print("dim_employee:", dim_employee.shape)
print("dim_employee_snapshot:", dim_employee_snapshot.shape)
print("dim_job_role:", dim_job_role.shape)
print("fact_attrition:", fact_attrition.shape)

dim_date: (4383, 10)
dim_department: (10, 2)
dim_employee: (45000, 13)
dim_employee_snapshot: (45000, 26)
dim_job_role: (23, 4)
fact_attrition: (4231, 11)

In [6]:
print(dim_date.head())

     DateID        Date  Year Quarter  MonthNumber MonthName MonthYear  \
0  20150101  2015-01-01  2015      Q1            1   January  Jan-2015
1  20150102  2015-01-02  2015      Q1            1   January  Jan-2015
2  20150103  2015-01-03  2015      Q1            1   January  Jan-2015
3  20150104  2015-01-04  2015      Q1            1   January  Jan-2015
4  20150105  2015-01-05  2015      Q1            1   January  Jan-2015

   WeekNumber   DayName  IsWeekend
0           1  Thursday      False
1           1    Friday      False
2           1  Saturday       True
3           1    Sunday       True
4           2    Monday      False

In [7]:
print(dim_date.tail())

        DateID        Date  Year Quarter  MonthNumber MonthName MonthYear  \
4378  20261227  2026-12-27  2026      Q4           12  December  Dec-2026
4379  20261228  2026-12-28  2026      Q4           12  December  Dec-2026
4380  20261229  2026-12-29  2026      Q4           12  December  Dec-2026
4381  20261230  2026-12-30  2026      Q4           12  December  Dec-2026
4382  20261231  2026-12-31  2026      Q4           12  December  Dec-2026

      WeekNumber    DayName  IsWeekend
4378          52     Sunday       True
4379          53     Monday      False
4380          53    Tuesday      False
4381          53  Wednesday      False
4382          53   Thursday      False

In [9]:
print(dim_date.info())

<class 'pandas.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DateID       4383 non-null   int64
 1   Date         4383 non-null   str
 2   Year         4383 non-null   int64
 3   Quarter      4383 non-null   str
 4   MonthNumber  4383 non-null   int64
 5   MonthName    4383 non-null   str
 6   MonthYear    4383 non-null   str
 7   WeekNumber   4383 non-null   int64
 8   DayName      4383 non-null   str
 9   IsWeekend    4383 non-null   bool
dtypes: bool(1), int64(4), str(5)
memory usage: 455.1 KB
None

In [10]:
print(dim_date.describe(include="all").T)

              count unique         top  freq             mean           std  \
DateID       4383.0    NaN         NaN   NaN  20205664.600274  34525.240746
Date           4383   4383  2015-01-01     1              NaN           NaN
Year         4383.0    NaN         NaN   NaN      2020.499658      3.452347
Quarter        4383      4          Q3  1104              NaN           NaN
MonthNumber  4383.0    NaN         NaN   NaN          6.52293      3.449097
MonthName      4383     12     January   372              NaN           NaN
MonthYear      4383    144    Jan-2015    31              NaN           NaN
WeekNumber   4383.0    NaN         NaN   NaN        26.626283     15.064988
DayName        4383      7    Thursday   627              NaN           NaN
IsWeekend      4383      2       False  3131              NaN           NaN

                    min         25%         50%         75%         max
DateID       20150101.0  20175666.0  20201231.0  20235666.0  20261231.0
Date                NaN         NaN         NaN         NaN         NaN
Year             2015.0      2017.5      2020.0      2023.5      2026.0
Quarter             NaN         NaN         NaN         NaN         NaN
MonthNumber         1.0         4.0         7.0        10.0        12.0
MonthName           NaN         NaN         NaN         NaN         NaN
MonthYear           NaN         NaN         NaN         NaN         NaN
WeekNumber          1.0        14.0        27.0        40.0        53.0
DayName             NaN         NaN         NaN         NaN         NaN
IsWeekend           NaN         NaN         NaN         NaN         NaN

In [11]:
print(dim_date.isna().sum())

DateID         0
Date           0
Year           0
Quarter        0
MonthNumber    0
MonthName      0
MonthYear      0
WeekNumber     0
DayName        0
IsWeekend      0
dtype: int64

In [12]:
print(dim_date.nunique())

DateID         4383
Date           4383
Year             12
Quarter           4
MonthNumber      12
MonthName        12
MonthYear       144
WeekNumber       53
DayName           7
IsWeekend         2
dtype: int64

In [13]:
print(dim_date.duplicated().sum())

0

In [15]:
print("\n9. CATEGORICAL VALUE COUNTS")

9. CATEGORICAL VALUE COUNTS

In [16]:
cat_cols = dim_date.select_dtypes(
    include=["object", "category"]
).columns

for col in cat_cols:
    print(f"\n===== {col} =====")
    print(dim_date[col].value_counts(dropna=False))

===== Date =====
Date
2015-01-01    1
2015-01-02    1
2015-01-03    1
2015-01-04    1
2015-01-05    1
             ..
2026-12-27    1
2026-12-28    1
2026-12-29    1
2026-12-30    1
2026-12-31    1
Name: count, Length: 4383, dtype: int64

===== Quarter =====
Quarter
Q3    1104
Q4    1104
Q2    1092
Q1    1083
Name: count, dtype: int64

===== MonthName =====
MonthName
January      372
March        372
May          372
July         372
August       372
October      372
December     372
April        360
June         360
September    360
November     360
February     339
Name: count, dtype: int64

===== MonthYear =====
MonthYear
Jan-2015    31
Mar-2015    31
May-2015    31
Jul-2015    31
Aug-2015    31
            ..
Feb-2021    28
Feb-2022    28
Feb-2023    28
Feb-2025    28
Feb-2026    28
Name: count, Length: 144, dtype: int64

===== DayName =====
DayName
Thursday     627
Friday       626
Saturday     626
Sunday       626
Monday       626
Tuesday      626
Wednesday    626
Name: count, dtype: int64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15860\2037825100.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = dim_date.select_dtypes(

In [17]:
 dim_department.shape

(10, 2)

In [18]:
dim_department.head()

  DepartmentID          DepartmentName
0          D01         Human Resources
1          D02                 Finance
2          D03                   Sales
3          D04               Marketing
4          D05  Information Technology

In [19]:
dim_department.tail()

  DepartmentID          DepartmentName
5          D06              Operations
6          D07        Customer Service
7          D08  Research & Development
8          D09                   Legal
9          D10             Procurement

In [20]:
dim_department.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DepartmentID    10 non-null     str
 1   DepartmentName  10 non-null     str
dtypes: str(2)
memory usage: 444.0 bytes

In [21]:
dim_department.describe(include="all")

       DepartmentID   DepartmentName
count            10               10
unique           10               10
top             D01  Human Resources
freq              1                1

In [22]:
dim_department.isna().sum()

DepartmentID      0
DepartmentName    0
dtype: int64

In [23]:
dim_department.nunique()

DepartmentID      10
DepartmentName    10
dtype: int64

In [24]:
dim_department.duplicated().sum()

np.int64(0)

# Categorical columns:

In [25]:
for col in dim_department.select_dtypes(include="object").columns:
    print(f"\n{col}")
    print(dim_department[col].value_counts(dropna=False))

DepartmentID
DepartmentID
D01    1
D02    1
D03    1
D04    1
D05    1
D06    1
D07    1
D08    1
D09    1
D10    1
Name: count, dtype: int64

DepartmentName
DepartmentName
Human Resources           1
Finance                   1
Sales                     1
Marketing                 1
Information Technology    1
Operations                1
Customer Service          1
Research & Development    1
Legal                     1
Procurement               1
Name: count, dtype: int64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15860\3752527980.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in dim_department.select_dtypes(include="object").columns:

In [26]:
dim_employee.shape

(45000, 13)

In [27]:
dim_employee.head()

,EmployeeID,FirstName,LastName,Gender,Age,Education,EducationField,MaritalStatus,City,State,DepartmentID,JobRoleID,EmploymentType
0,E00001,Muskan,Sinha,Female,27,Master's,Engineering,Married,Noida,Uttar Pradesh,D02,JR03,Full-Time
1,E00002,Simran,Khan,Male,39,Bachelor's,Life Sciences,Divorced,Indore,Madhya Pradesh,D04,JR07,Contract
2,E00003,Meera,Yadav,Male,32,Bachelor's,Humanities,Single,Bengaluru,Karnataka,D01,JR02,Full-Time
3,E00004,Anaya,Joshi,Female,25,MBA,Humanities,Single,Noida,Uttar Pradesh,D04,JR08,Full-Time
4,E00005,Rahul,Verma,Female,31,MBA,Computer Science,Married,Noida,Uttar Pradesh,D07,JR17,Full-Time

In [28]:
dim_employee.tail()

,EmployeeID,FirstName,LastName,Gender,Age,Education,EducationField,MaritalStatus,City,State,DepartmentID,JobRoleID,EmploymentType
44995,E44996,Pooja,Bansal,Male,29,Master's,Computer Science,Married,Bhopal,Madhya Pradesh,D05,JR12,Full-Time
44996,E44997,Karan,Malhotra,Female,30,Master's,Other,Divorced,Mumbai,Maharashtra,D05,JR12,Full-Time
44997,E44998,Yash,Gupta,Female,27,High School,Computer Science,Married,Chennai,Tamil Nadu,D05,JR10,Full-Time
44998,E44999,Kabir,Sharma,Female,29,Bachelor's,Computer Science,Divorced,Delhi,Delhi,D07,JR17,Full-Time
44999,E45000,Ishaan,Yadav,Female,26,Master's,Computer Science,Single,Gurugram,Haryana,D07,JR17,Full-Time

In [29]:
dim_employee.info()

<class 'pandas.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EmployeeID      45000 non-null  str
 1   FirstName       45000 non-null  str
 2   LastName        45000 non-null  str
 3   Gender          45000 non-null  str
 4   Age             45000 non-null  int64
 5   Education       45000 non-null  str
 6   EducationField  45000 non-null  str
 7   MaritalStatus   45000 non-null  str
 8   City            45000 non-null  str
 9   State           45000 non-null  str
 10  DepartmentID    45000 non-null  str
 11  JobRoleID       45000 non-null  str
 12  EmploymentType  45000 non-null  str
dtypes: int64(1), str(12)
memory usage: 7.9 MB

In [30]:
dim_employee.describe(include="all")

,EmployeeID,FirstName,LastName,Gender,Age,Education,EducationField,MaritalStatus,City,State,DepartmentID,JobRoleID,EmploymentType
count,45000,45000,45000,45000,45000.000000,45000,45000,45000,45000,45000,45000,45000,45000
unique,45000,40,20,2,NaN,5,8,3,12,9,10,23,3
top,E00001,Karan,Gupta,Male,NaN,Bachelor's,Computer Science,Married,Pune,Maharashtra,D03,JR05,Full-Time
freq,1,1206,2318,25152,NaN,21590,9840,22562,3851,7577,8050,4102,35141
mean,NaN,NaN,NaN,NaN,34.235778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,7.590242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,21.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,34.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
dim_employee.isna().sum()

EmployeeID        0
FirstName         0
LastName          0
Gender            0
Age               0
Education         0
EducationField    0
MaritalStatus     0
City              0
State             0
DepartmentID      0
JobRoleID         0
EmploymentType    0
dtype: int64

In [32]:
dim_employee.nunique()

EmployeeID        45000
FirstName            40
LastName             20
Gender                2
Age                  40
Education             5
EducationField        8
MaritalStatus         3
City                 12
State                 9
DepartmentID         10
JobRoleID            23
EmploymentType        3
dtype: int64

In [33]:
dim_employee.duplicated().sum()

np.int64(0)

# Categorical columns:

In [34]:
for col in dim_employee.select_dtypes(include="object").columns:
    print(f"\n===== {col} =====")
    print(dim_employee[col].value_counts(dropna=False))

===== EmployeeID =====
EmployeeID
E00001    1
E00002    1
E00003    1
E00004    1
E00005    1
         ..
E44996    1
E44997    1
E44998    1
E44999    1
E45000    1
Name: count, Length: 45000, dtype: int64

===== FirstName =====
FirstName
Karan      1206
Ira        1206
Riya       1197
Pooja      1189
Sneha      1166
Meera      1161
Simran     1155
Nitin      1151
Muskan     1148
Shreya     1148
Arjun      1146
Tanya      1144
Diya       1143
Anika      1142
Rahul      1132
Kavya      1128
Aditya     1126
Anaya      1125
Rohan      1123
Vivaan     1123
Amit       1122
Aanya      1120
Reyansh    1118
Vikram     1114
Kabir      1107
Manish     1105
Ritika     1104
Sahil      1104
Nisha      1102
Ishaan     1095
Atharv     1095
Saanvi     1094
Vihaan     1091
Priya      1090
Varun      1083
Akash      1083
Ankit      1082
Neha       1081
Aarav      1081
Yash       1070
Name: count, dtype: int64

===== LastName =====
LastName
Gupta         2318
Verma         2293
Yadav         2292
Mishra        2286
Saxena        2281
Mehta         2269
Sharma        2269
Singh         2263
Rao           2261
Sinha         2258
Joshi         2256
Malhotra      2245
Chauhan       2244
Agarwal       2232
Khan          2230
Jain          2226
Patel         2217
Srivastava    2211
Bansal        2187
Tiwari        2162
Name: count, dtype: int64

===== Gender =====
Gender
Male      25152
Female    19848
Name: count, dtype: int64

===== Education =====
Education
Bachelor's     21590
Master's       11299
MBA             7135
High School     3642
PhD             1334
Name: count, dtype: int64

===== EducationField =====
EducationField
Computer Science    9840
Engineering         9050
Business            6707
Marketing           4604
Finance             4441
Life Sciences       3699
Humanities          3541
Other               3118
Name: count, dtype: int64

===== MaritalStatus =====
MaritalStatus
Married     22562
Single      18813
Divorced     3625
Name: count, dtype: int64

===== City =====
City
Pune         3851
Hyderabad    3821
Chennai      3803
Bhopal       3772
Jaipur       3757
Lucknow      3752
Delhi        3743
Gurugram     3732
Mumbai       3726
Indore       3720
Bengaluru    3712
Noida        3611
Name: count, dtype: int64

===== State =====
State
Maharashtra       7577
Madhya Pradesh    7492
Uttar Pradesh     7363
Telangana         3821
Tamil Nadu        3803
Rajasthan         3757
Delhi             3743
Haryana           3732
Karnataka         3712
Name: count, dtype: int64

===== DepartmentID =====
DepartmentID
D03    8050
D05    7999
D06    6266
D07    5452
D04    3640
D08    3636
D02    3174
D01    2774
D10    2613
D09    1396
Name: count, dtype: int64

===== JobRoleID =====
JobRoleID
JR05    4102
JR06    3948
JR14    3143
JR15    3123
JR17    2763
JR16    2689
JR08    1841
JR18    1841
JR07    1799
JR19    1795
JR10    1654
JR09    1619
JR13    1614
JR03    1607
JR11    1598
JR04    1567
JR12    1514
JR02    1407
JR01    1367
JR23    1344
JR22    1269
JR20     714
JR21     682
Name: count, dtype: int64

===== EmploymentType =====
EmploymentType
Full-Time    35141
Contract      6240
Part-Time     3619
Name: count, dtype: int64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15860\2722187171.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in dim_employee.select_dtypes(include="object").columns:

In [35]:
dim_employee_snapshot.shape

(45000, 26)

In [37]:
dim_employee_snapshot.tail()

,EmployeeID,DepartmentID,JobRoleID,City,EmploymentType,HireDate,ExitDate,Status,Attrition,Age,...,JobSatisfaction,WorkLifeBalance,EnvironmentSatisfaction,OverTime,TrainingHours,NumCompaniesWorked,JobInvolvement,BusinessTravel,HireDateID,ExitDateID
44995,E44996,D05,JR12,Bhopal,Full-Time,7/2/2025,NaN,Active,No,29,...,4,3,3,Yes,46,1,4,Travel_Rarely,20250702,0
44996,E44997,D05,JR12,Mumbai,Full-Time,3/19/2016,NaN,Active,No,30,...,4,3,2,No,25,1,5,Travel_Rarely,20160319,0
44997,E44998,D05,JR10,Chennai,Full-Time,6/16/2023,NaN,Active,No,27,...,3,4,3,No,57,2,5,Travel_Rarely,20230616,0
44998,E44999,D07,JR17,Delhi,Full-Time,8/14/2015,NaN,Active,No,29,...,4,4,3,Yes,51,0,4,Travel_Rarely,20150814,0
44999,E45000,D07,JR17,Gurugram,Full-Time,9/9/2022,NaN,Active,No,26,...,2,2,3,No,40,5,4,Travel_Rarely,20220909,0

In [38]:
dim_employee_snapshot.info()

<class 'pandas.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EmployeeID               45000 non-null  str
 1   DepartmentID             45000 non-null  str
 2   JobRoleID                45000 non-null  str
 3   City                     45000 non-null  str
 4   EmploymentType           45000 non-null  str
 5   HireDate                 45000 non-null  str
 6   ExitDate                 4231 non-null   str
 7   Status                   45000 non-null  str
 8   Attrition                45000 non-null  str
 9   Age                      45000 non-null  int64
 10  YearsAtCompany           45000 non-null  float64
 11  YearsInCurrentRole       45000 non-null  float64
 12  YearsSinceLastPromotion  45000 non-null  float64
 13  MonthlyIncome            45000 non-null  int64
 14  PercentSalaryHike        45000 non-null  int64
 15  PerformanceRating        45000 non-null  int64
 16  JobSatisfaction          45000 non-null  int64
 17  WorkLifeBalance          45000 non-null  int64
 18  EnvironmentSatisfaction  45000 non-null  int64
 19  OverTime                 45000 non-null  str
 20  TrainingHours            45000 non-null  int64
 21  NumCompaniesWorked       45000 non-null  int64
 22  JobInvolvement           45000 non-null  int64
 23  BusinessTravel           45000 non-null  str
 24  HireDateID               45000 non-null  int64
 25  ExitDateID               45000 non-null  int64
dtypes: float64(3), int64(12), str(11)
memory usage: 11.6 MB

In [39]:
dim_employee_snapshot.describe(include="all")

,EmployeeID,DepartmentID,JobRoleID,City,EmploymentType,HireDate,ExitDate,Status,Attrition,Age,...,JobSatisfaction,WorkLifeBalance,EnvironmentSatisfaction,OverTime,TrainingHours,NumCompaniesWorked,JobInvolvement,BusinessTravel,HireDateID,ExitDateID
count,45000,45000,45000,45000,45000,45000,4231,45000,45000,45000.000000,...,45000.000000,45000.000000,45000.000000,45000,45000.000000,45000.000000,45000.000000,45000,4.500000e+04,4.500000e+04
unique,45000,10,23,12,3,4018,1866,2,2,NaN,...,NaN,NaN,NaN,2,NaN,NaN,NaN,3,NaN,NaN
top,E00001,D03,JR05,Pune,Full-Time,3/13/2025,5/11/2026,Active,No,NaN,...,NaN,NaN,NaN,No,NaN,NaN,NaN,Travel_Rarely,NaN,NaN
freq,1,8050,4102,3851,35141,25,11,40769,40769,NaN,...,NaN,NaN,NaN,32345,NaN,NaN,NaN,31603,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.235778,...,3.284556,3.410111,3.390267,NaN,30.010311,2.998756,3.314422,NaN,2.020080e+07,1.902885e+06
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.590242,...,1.038614,1.039952,1.030568,NaN,17.627389,2.007198,0.944918,NaN,3.151561e+04,5.906919e+06
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.000000,...,1.000000,1.000000,1.000000,NaN,0.000000,0.000000,1.000000,NaN,2.015010e+07,0.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,...,3.000000,3.000000,3.000000,NaN,15.000000,1.000000,3.000000,NaN,2.017101e+07,0.000000e+00
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.000000,...,3.000000,3.000000,3.000000,NaN,30.000000,3.000000,3.000000,NaN,2.020070e+07,0.000000e+00
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.000000,...,4.000000,4.000000,4.000000,NaN,45.000000,5.000000,4.000000,NaN,2.023033e+07,0.000000e+00
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.000000,...,5.000000,5.000000,5.000000,NaN,60.000000,6.000000,5.000000,NaN,2.025123e+07,2.026073e+07

In [40]:
dim_employee_snapshot.isna().sum()

EmployeeID                     0
DepartmentID                   0
JobRoleID                      0
City                           0
EmploymentType                 0
HireDate                       0
ExitDate                   40769
Status                         0
Attrition                      0
Age                            0
YearsAtCompany                 0
YearsInCurrentRole             0
YearsSinceLastPromotion        0
MonthlyIncome                  0
PercentSalaryHike              0
PerformanceRating              0
JobSatisfaction                0
WorkLifeBalance                0
EnvironmentSatisfaction        0
OverTime                       0
TrainingHours                  0
NumCompaniesWorked             0
JobInvolvement                 0
BusinessTravel                 0
HireDateID                     0
ExitDateID                     0
dtype: int64

In [41]:
dim_employee_snapshot.nunique()

EmployeeID                 45000
DepartmentID                  10
JobRoleID                     23
City                          12
EmploymentType                 3
HireDate                    4018
ExitDate                    1866
Status                         2
Attrition                      2
Age                           40
YearsAtCompany               110
YearsInCurrentRole            70
YearsSinceLastPromotion       61
MonthlyIncome              34578
PercentSalaryHike             16
PerformanceRating              5
JobSatisfaction                5
WorkLifeBalance                5
EnvironmentSatisfaction        5
OverTime                       2
TrainingHours                 61
NumCompaniesWorked             7
JobInvolvement                 5
BusinessTravel                 3
HireDateID                  4018
ExitDateID                  1867
dtype: int64

In [42]:
dim_employee_snapshot.duplicated().sum()

np.int64(0)

# Categorical columns

In [43]:
for col in dim_employee_snapshot.select_dtypes(include="object").columns:
    print(f"\n===== {col} =====")
    print(dim_employee_snapshot[col].value_counts(dropna=False))

===== EmployeeID =====
EmployeeID
E00001    1
E00002    1
E00003    1
E00004    1
E00005    1
         ..
E44996    1
E44997    1
E44998    1
E44999    1
E45000    1
Name: count, Length: 45000, dtype: int64

===== DepartmentID =====
DepartmentID
D03    8050
D05    7999
D06    6266
D07    5452
D04    3640
D08    3636
D02    3174
D01    2774
D10    2613
D09    1396
Name: count, dtype: int64

===== JobRoleID =====
JobRoleID
JR05    4102
JR06    3948
JR14    3143
JR15    3123
JR17    2763
JR16    2689
JR08    1841
JR18    1841
JR07    1799
JR19    1795
JR10    1654
JR09    1619
JR13    1614
JR03    1607
JR11    1598
JR04    1567
JR12    1514
JR02    1407
JR01    1367
JR23    1344
JR22    1269
JR20     714
JR21     682
Name: count, dtype: int64

===== City =====
City
Pune         3851
Hyderabad    3821
Chennai      3803
Bhopal       3772
Jaipur       3757
Lucknow      3752
Delhi        3743
Gurugram     3732
Mumbai       3726
Indore       3720
Bengaluru    3712
Noida        3611
Name: count, dtype: int64

===== EmploymentType =====
EmploymentType
Full-Time    35141
Contract      6240
Part-Time     3619
Name: count, dtype: int64

===== HireDate =====
HireDate
3/13/2025     25
9/2/2025      24
8/9/2018      24
1/5/2021      23
11/7/2020     23
              ..
3/13/2018      3
7/28/2023      3
3/15/2024      3
3/7/2016       3
12/29/2022     2
Name: count, Length: 4018, dtype: int64

===== ExitDate =====
ExitDate
NaN           40769
5/11/2026        11
3/9/2026         10
11/22/2025        9
5/19/2026         9
              ...
1/16/2020         1
4/20/2025         1
8/7/2021          1
8/27/2022         1
10/7/2021         1
Name: count, Length: 1867, dtype: int64

===== Status =====
Status
Active    40769
Exited     4231
Name: count, dtype: int64

===== Attrition =====
Attrition
No     40769
Yes     4231
Name: count, dtype: int64

===== OverTime =====
OverTime
No     32345
Yes    12655
Name: count, dtype: int64

===== BusinessTravel =====
BusinessTravel
Travel_Rarely        31603
Travel_Frequently     7974
Non-Travel            5423
Name: count, dtype: int64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15860\3825889972.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in dim_employee_snapshot.select_dtypes(include="object").columns:

In [44]:
dim_job_role.shape

(23, 4)

In [45]:
dim_job_role.head()

  JobRoleID DepartmentGroup            JobRole DepartmentID
0      JR01              HR       HR Executive          D01
1      JR02              HR         HR Manager          D01
2      JR03         Finance  Financial Analyst          D02
3      JR04         Finance    Finance Manager          D02
4      JR05           Sales    Sales Executive          D03

In [46]:
dim_job_role.tail()

   JobRoleID DepartmentGroup                JobRole DepartmentID
18      JR19             R&D      Research Engineer          D08
19      JR20           Legal        Legal Associate          D09
20      JR21           Legal          Legal Manager          D09
21      JR22     Procurement  Procurement Executive          D10
22      JR23     Procurement    Procurement Manager          D10

In [47]:
dim_job_role.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   JobRoleID        23 non-null     str
 1   DepartmentGroup  23 non-null     str
 2   JobRole          23 non-null     str
 3   DepartmentID     23 non-null     str
dtypes: str(4)
memory usage: 1.5 KB

In [48]:
dim_job_role.describe(include="all")

       JobRoleID DepartmentGroup       JobRole DepartmentID
count         23              23            23           23
unique        23              10            23           10
top         JR01              IT  HR Executive          D05
freq           1               5             1            5

In [49]:
dim_job_role.isna().sum()

JobRoleID          0
DepartmentGroup    0
JobRole            0
DepartmentID       0
dtype: int64

In [50]:
dim_job_role.nunique()

JobRoleID          23
DepartmentGroup    10
JobRole            23
DepartmentID       10
dtype: int64

In [51]:
dim_job_role.duplicated().sum()

np.int64(0)

# Categorical columns value_counts()

In [52]:
for col in dim_job_role.select_dtypes(include="object").columns:
    print(f"\n===== {col} =====")
    print(dim_job_role[col].value_counts(dropna=False))

===== JobRoleID =====
JobRoleID
JR01    1
JR02    1
JR03    1
JR04    1
JR05    1
JR06    1
JR07    1
JR08    1
JR09    1
JR10    1
JR11    1
JR12    1
JR13    1
JR14    1
JR15    1
JR16    1
JR17    1
JR18    1
JR19    1
JR20    1
JR21    1
JR22    1
JR23    1
Name: count, dtype: int64

===== DepartmentGroup =====
DepartmentGroup
IT                  5
HR                  2
Finance             2
Sales               2
Marketing           2
Operations          2
Customer Service    2
R&D                 2
Legal               2
Procurement         2
Name: count, dtype: int64

===== JobRole =====
JobRole
HR Executive                       1
HR Manager                         1
Financial Analyst                  1
Finance Manager                    1
Sales Executive                    1
Sales Manager                      1
Marketing Executive                1
Marketing Manager                  1
Software Engineer                  1
Data Analyst                       1
Data Scientist                     1
IT Support Specialist              1
Project Manager                    1
Operations Executive               1
Operations Manager                 1
Customer Service Representative    1
Customer Service Manager           1
Research Scientist                 1
Research Engineer                  1
Legal Associate                    1
Legal Manager                      1
Procurement Executive              1
Procurement Manager                1
Name: count, dtype: int64

===== DepartmentID =====
DepartmentID
D05    5
D01    2
D02    2
D03    2
D04    2
D06    2
D07    2
D08    2
D09    2
D10    2
Name: count, dtype: int64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15860\3070054714.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in dim_job_role.select_dtypes(include="object").columns:

In [53]:
fact_attrition.shape

(4231, 11)

In [54]:
fact_attrition.head()

,EmployeeID,DepartmentID,JobRoleID,HireDate,ExitDate,ExitReason,ExitType,NoticePeriodDays,ExitInterviewCompleted,HireDateID,ExitDateID
0,E00007,D01,JR01,8/28/2019,11/9/2023,Career Growth,Involuntary,30,Yes,20190828,20231109
1,E00012,D06,JR15,3/26/2023,5/29/2024,Work-Life Balance,Voluntary,45,Yes,20230326,20240529
2,E00019,D07,JR16,6/18/2023,12/19/2025,Better Opportunity,Voluntary,45,Yes,20230618,20251219
3,E00047,D05,JR10,11/16/2015,1/27/2023,Career Growth,Voluntary,45,Yes,20151116,20230127
4,E00062,D03,JR06,7/9/2015,1/10/2020,Compensation,Voluntary,45,Yes,20150709,20200110

In [55]:
fact_attrition.tail()

,EmployeeID,DepartmentID,JobRoleID,HireDate,ExitDate,ExitReason,ExitType,NoticePeriodDays,ExitInterviewCompleted,HireDateID,ExitDateID
4226,E44964,D05,JR11,10/12/2020,8/27/2022,Work-Life Balance,Voluntary,30,Yes,20201012,20220827
4227,E44965,D03,JR05,11/10/2018,7/11/2024,Manager/Leadership,Voluntary,45,Yes,20181110,20240711
4228,E44984,D04,JR08,8/26/2022,8/10/2025,Better Opportunity,Voluntary,45,Yes,20220826,20250810
4229,E44989,D06,JR14,9/12/2018,10/7/2021,Better Opportunity,Voluntary,45,Yes,20180912,20211007
4230,E44991,D08,JR18,9/26/2021,5/28/2024,Work-Life Balance,Voluntary,45,Yes,20210926,20240528

In [56]:
fact_attrition.info()

<class 'pandas.DataFrame'>
RangeIndex: 4231 entries, 0 to 4230
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EmployeeID              4231 non-null   str
 1   DepartmentID            4231 non-null   str
 2   JobRoleID               4231 non-null   str
 3   HireDate                4231 non-null   str
 4   ExitDate                4231 non-null   str
 5   ExitReason              4231 non-null   str
 6   ExitType                4231 non-null   str
 7   NoticePeriodDays        4231 non-null   int64
 8   ExitInterviewCompleted  4231 non-null   str
 9   HireDateID              4231 non-null   int64
 10  ExitDateID              4231 non-null   int64
dtypes: int64(3), str(8)
memory usage: 605.7 KB

In [57]:
fact_attrition.info()

<class 'pandas.DataFrame'>
RangeIndex: 4231 entries, 0 to 4230
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EmployeeID              4231 non-null   str
 1   DepartmentID            4231 non-null   str
 2   JobRoleID               4231 non-null   str
 3   HireDate                4231 non-null   str
 4   ExitDate                4231 non-null   str
 5   ExitReason              4231 non-null   str
 6   ExitType                4231 non-null   str
 7   NoticePeriodDays        4231 non-null   int64
 8   ExitInterviewCompleted  4231 non-null   str
 9   HireDateID              4231 non-null   int64
 10  ExitDateID              4231 non-null   int64
dtypes: int64(3), str(8)
memory usage: 605.7 KB

In [58]:
fact_attrition.describe(include="all")

,EmployeeID,DepartmentID,JobRoleID,HireDate,ExitDate,ExitReason,ExitType,NoticePeriodDays,ExitInterviewCompleted,HireDateID,ExitDateID
count,4231,4231,4231,4231,4231,4231,4231,4231.000000,4231,4.231000e+03,4.231000e+03
unique,4231,10,23,2624,1866,8,2,NaN,2,NaN,NaN
top,E00007,D05,JR05,5/24/2022,5/11/2026,Better Opportunity,Voluntary,NaN,Yes,NaN,NaN
freq,1,760,381,7,11,1015,3523,NaN,3722,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.430867,NaN,2.019978e+07,2.023867e+07
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.723103,NaN,3.160387e+04,1.946358e+04
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,2.015010e+07,2.017122e+07
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,NaN,2.017091e+07,2.023021e+07
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,NaN,2.020041e+07,2.024102e+07
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.000000,NaN,2.023012e+07,2.025112e+07
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.000000,NaN,2.025123e+07,2.026073e+07

In [59]:
fact_attrition.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
EmployeeID,4231,4231,E00007,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DepartmentID,4231,10,D05,760,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JobRoleID,4231,23,JR05,381,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HireDate,4231,2624,5/24/2022,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ExitDate,4231,1866,5/11/2026,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ExitReason,4231,8,Better Opportunity,1015,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ExitType,4231,2,Voluntary,3523,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NoticePeriodDays,4231.0,NaN,NaN,NaN,37.430867,15.723103,15.0,30.0,30.0,45.0,90.0
ExitInterviewCompleted,4231,2,Yes,3722,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HireDateID,4231.0,NaN,NaN,NaN,20199777.8277,31603.867283,20150101.0,20170911.0,20200411.0,20230125.0,20251231.0
ExitDateID,4231.0,NaN,NaN,NaN,20238669.562987,19463.579233,20171225.0,20230214.5,20241016.0,20251119.0,20260731.0

In [60]:
fact_attrition.isna().sum()

EmployeeID                0
DepartmentID              0
JobRoleID                 0
HireDate                  0
ExitDate                  0
ExitReason                0
ExitType                  0
NoticePeriodDays          0
ExitInterviewCompleted    0
HireDateID                0
ExitDateID                0
dtype: int64

In [61]:
fact_attrition.nunique()

EmployeeID                4231
DepartmentID                10
JobRoleID                   23
HireDate                  2624
ExitDate                  1866
ExitReason                   8
ExitType                     2
NoticePeriodDays             5
ExitInterviewCompleted       2
HireDateID                2624
ExitDateID                1866
dtype: int64

In [62]:
fact_attrition.duplicated().sum()

np.int64(0)

In [63]:
for col in fact_attrition.select_dtypes(include="object").columns:
    print(f"\n===== {col} =====")
    print(fact_attrition[col].value_counts(dropna=False))

===== EmployeeID =====
EmployeeID
E00007    1
E00012    1
E00019    1
E00047    1
E00062    1
         ..
E44964    1
E44965    1
E44984    1
E44989    1
E44991    1
Name: count, Length: 4231, dtype: int64

===== DepartmentID =====
DepartmentID
D05    760
D03    746
D07    566
D06    557
D04    340
D08    337
D02    297
D01    252
D10    236
D09    140
Name: count, dtype: int64

===== JobRoleID =====
JobRoleID
JR05    381
JR06    365
JR17    298
JR15    289
JR16    268
JR14    268
JR18    184
JR08    171
JR07    169
JR10    164
JR09    160
JR03    157
JR11    156
JR19    153
JR13    147
JR04    140
JR12    133
JR01    129
JR02    123
JR22    120
JR23    116
JR20     72
JR21     68
Name: count, dtype: int64

===== HireDate =====
HireDate
5/24/2022     7
12/14/2017    7
12/12/2017    6
6/25/2021     6
6/12/2022     6
             ..
1/22/2021     1
3/5/2025      1
10/12/2020    1
11/10/2018    1
9/12/2018     1
Name: count, Length: 2624, dtype: int64

===== ExitDate =====
ExitDate
5/11/2026     11
3/9/2026      10
11/22/2025     9
5/19/2026      9
7/26/2026      9
              ..
1/16/2020      1
4/20/2025      1
8/7/2021       1
8/27/2022      1
10/7/2021      1
Name: count, Length: 1866, dtype: int64

===== ExitReason =====
ExitReason
Better Opportunity     1015
Compensation            719
Work-Life Balance       568
Career Growth           525
Manager/Leadership      432
Relocation              354
Personal Reasons        351
Job Dissatisfaction     267
Name: count, dtype: int64

===== ExitType =====
ExitType
Voluntary      3523
Involuntary     708
Name: count, dtype: int64

===== ExitInterviewCompleted =====
ExitInterviewCompleted
Yes    3722
No      509
Name: count, dtype: int64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15860\1928732210.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in fact_attrition.select_dtypes(include="object").columns: